#!/usr/bin/env python
# -*- coding: utf8 -*-
from simple_backup.app.backup import backup_db, backup_db_per_table
import argparse


def main():
    parser = argparse.ArgumentParser(description='Example with long option names')
    group1 = parser.add_mutually_exclusive_group()
    group1.add_argument('-D', '--dump', action="count", dest="dump", help='Backup type is DUMP')
    group1.add_argument('-H', '--hotcopy', action="count", dest="hotcopy", help='Backup type is Hotcopy')
    group1.add_argument('-T', '--tables', action="count", dest="dump_per_table", help='Backup type is Dump per table')
    group2 = parser.add_mutually_exclusive_group()
    group2.add_argument('-hr', '--hour', action="count", dest="hour", help='Hour backup')
    group2.add_argument('-d', '--day', action="count",  dest="day", help='Day backup')
    group2.add_argument('-w', '--week', action="count",  dest="week", help='Week backup')
    group2.add_argument('-m', '--month', action="count",  dest="month", help='Month backup')
    results = parser.parse_args()
    if results.dump:
        if results.hour:
            backup_db('hr_', 30, 'dump')
        elif results.day:
            backup_db('dl_', 7, 'dump')
        elif results.week:
            backup_db('wk_', 4, 'dump')
        elif results.month:
            backup_db('mnt_', 3, 'dump')
        else:
            print parser.print_help()
    elif results.hotcopy:
        if results.hour:
            backup_db('hr_', 30, 'hotcopy')
        elif results.day:
            backup_db('dl_', 7, 'hotcopy')
        elif results.week:
            backup_db('wk_', 4, 'hotcopy')
        elif results.month:
            backup_db('mnt_', 3, 'hotcopy')
        else:
            print parser.print_help()
    elif results.dump_per_table:
        if results.hour:
            backup_db_per_table('hr_', 30, 'dump')
        elif results.day:
            backup_db_per_table('dl_', 7, 'dump')
        elif results.week:
            backup_db_per_table('wk_', 4, 'dump')
        elif results.month:
            backup_db_per_table('mnt_', 3, 'dump')
        else:
            print parser.print_help()
    else:
        print parser.print_help()

if __name__ == "__main__":
    main()
